package com.svnavigatoru600.repository.forum;

import java.util.List;

import com.svnavigatoru600.domain.forum.Contribution;
import com.svnavigatoru600.repository.MapperInterface;
import com.svnavigatoru600.repository.forum.impl.ContributionField;
import com.svnavigatoru600.service.util.OrderType;

/**
 * @author <a href="mailto:skalicky.tomas@gmail.com">Tomas Skalicky</a>
 */
@MapperInterface
public interface ContributionDao {

    /**
     * Returns a {@link Contribution} stored in the repository which has the given ID.
     */
    Contribution findById(int contributionId);

    /**
     * Returns all {@link Contribution Contributions} stored in the repository which belong to the specified
     * {@link com.svnavigatoru600.domain.forum.Thread thread}.
     * 
     * @param threadId
     *            The ID of the thread
     */
    List<Contribution> findAll(int threadId);

    /**
     * Returns all {@link Contribution Contributions} stored in the repository arranged according to the given
     * {@link ContributionField sortField} and {@link OrderType sortDirection}.
     * <p>
     * It returns only the first <code>maxResultSize</code> {@link Contribution Contributions}.
     */
    List<Contribution> findAllOrdered(ContributionField sortField, OrderType sortDirection, int maxResultSize);

    /**
     * Returns all {@link Contribution Contributions} stored in the repository arranged according to the given
     * {@link ContributionField sortField} and {@link OrderType sortDirection}.
     * <p>
     * Moreover, the resulting {@link Contribution Contributions} are only those which belong to the specified
     * {@link com.svnavigatoru600.domain.forum.Thread Thread}.
     * 
     * @param threadId
     *            The ID of the thread
     */
    List<Contribution> findAllOrdered(int threadId, ContributionField sortField, OrderType sortDirection);

    /**
     * Updates the given {@link Contribution} in the repository. The old version of this contribution should
     * be already stored there.
     */
    void update(Contribution contribution);

    /**
     * Stores the given {@link Contribution} to the repository.
     * 
     * @return The new ID of the given {@link Contribution} generated by the repository
     */
    int save(Contribution contribution);

    /**
     * Deletes the given {@link Contribution} from the repository.
     */
    void delete(Contribution contribution);
}
