package com.svnavigatoru600.repository.forum;

import java.util.List;

import com.svnavigatoru600.domain.forum.Thread;
import com.svnavigatoru600.repository.MapperInterface;

/**
 * @author <a href="mailto:skalicky.tomas@gmail.com">Tomas Skalicky</a>
 */
@MapperInterface
public interface ThreadDao {

    /**
     * Returns a {@link Thread} stored in the repository which has the given ID.
     * <p>
     * The returned thread has its {@link Thread#getAuthor() author} and {@link Thread#getContributions()
     * contributions} populated.
     */
    Thread findById(int threadId);

    /**
     * Returns all {@link Thread Threads} stored in the repository.
     * <p>
     * Returned threads have their {@link Thread#getAuthor() authors} and {@link Thread#getContributions()
     * contributions} populated.
     */
    List<Thread> loadAll();

    /**
     * Updates the given {@link Thread} in the repository. The old version of this thread should be already
     * stored there.
     * <p>
     * Does not persist neither new {@link com.svnavigatoru600.domain.users.User User} object, nor new
     * {@link com.svnavigatoru600.domain.forum.Contribution Contribution} one, but links to already-existing
     * repository records. Does persist changes of <code>thread</code>'s {@link Thread#getAuthor() author},
     * but does NOT persist changes of <code>thread</code>'s {@link Thread#getContributions() contributions}.
     */
    void update(Thread thread);

    /**
     * Stores the given {@link Thread} to the repository.
     * <p>
     * Does persist <code>thread</code>'s {@link Thread#getContributions() contributions} as new records in
     * the repository. Record of <code>thread</code>'s {@link Thread#getAuthor() author} must have been
     * already stored in the repository; otherwise, an exception is thrown.
     * 
     * @return The new ID of the given {@link Thread} generated by the repository
     */
    int save(Thread thread);

    /**
     * Deletes the given {@link Thread} from the repository.
     * <p>
     * Deletes records of <code>thread</code>'s {@link Thread#getContributions() contributions} from the
     * repository as well.
     */
    void delete(Thread thread);
}
