package com.svnavigatoru600.repository.forum;

import java.util.List;

import com.svnavigatoru600.domain.forum.ForumThread;

/**
 * @author <a href="mailto:skalicky.tomas@gmail.com">Tomas Skalicky</a>
 */
public interface ThreadDao {

    /**
     * Returns a {@link ForumThread} stored in the repository which has the given ID.
     * <p>
     * The returned thread has its {@link ForumThread#getAuthor() author} and {@link ForumThread#getContributions() contributions}
     * populated.
     */
    ForumThread findById(int threadId);

    /**
     * Returns all {@link ForumThread Threads} stored in the repository.
     * <p>
     * Returned threads have their {@link ForumThread#getAuthor() authors} and {@link ForumThread#getContributions()
     * contributions} populated.
     */
    List<ForumThread> loadAll();

    /**
     * Updates the given {@link ForumThread} in the repository. The old version of this thread should be already stored
     * there.
     * <p>
     * Does NOT persist changes of <code>thread</code>'s {@link ForumThread#getContributions() contributions}.
     * <p>
     * <b>Preconditions:</b> The new <code>thread</code>'s {@link ForumThread#getAuthor() author} must have already been
     * persisted in the repository.
     */
    void update(ForumThread thread);

    /**
     * Stores the given {@link ForumThread} to the repository.
     * <p>
     * Does persist <code>thread</code>'s {@link ForumThread#getContributions() contributions} as new records in the
     * repository.
     * <p>
     * <b>Preconditions:</b> The new <code>thread</code>'s {@link ForumThread#getAuthor() author} must have already been
     * persisted in the repository.
     * 
     * @return The new ID of the given {@link ForumThread} generated by the repository
     */
    int save(ForumThread thread);

    /**
     * Deletes the given {@link ForumThread} from the repository.
     * <p>
     * Deletes records of <code>thread</code>'s {@link ForumThread#getContributions() contributions} from the repository as
     * well.
     */
    void delete(ForumThread thread);
}
