package com.svnavigatoru600.repository;

import java.util.Date;
import java.util.List;

import com.svnavigatoru600.domain.eventcalendar.CalendarEvent;
import com.svnavigatoru600.service.util.OrderType;

/**
 * @author <a href="mailto:skalicky.tomas@gmail.com">Tomas Skalicky</a>
 */
public interface CalendarEventDao {

    /**
     * Returns a {@link CalendarEvent} stored in the repository which has the given ID.
     */
    CalendarEvent findById(int eventId);

    /**
     * Returns all {@link CalendarEvent CalendarEvents} stored in the repository arranged according to their
     * {@link CalendarEvent#getDate() date} in the given {@link OrderType sortDirection}.
     * <p>
     * Moreover, only {@link CalendarEvent CalendarEvents} which will take place are returned, the passed ones are not.
     * 
     * @param earliestDate
     *            Represents the time "now"
     */
    List<CalendarEvent> findAllFutureEventsOrdered(Date earliestDate, OrderType sortDirection);

    /**
     * Updates the given {@link CalendarEvent} in the repository. The old version of this event should be already stored
     * there.
     */
    void update(CalendarEvent event);

    /**
     * Stores the given {@link CalendarEvent} to the repository.
     * 
     * @return The new ID of the given {@link CalendarEvent} generated by the repository
     */
    int save(CalendarEvent event);

    /**
     * Deletes the given {@link CalendarEvent} from the repository.
     */
    void delete(CalendarEvent event);
}
