package com.svnavigatoru600.repository;

import java.util.List;

import com.svnavigatoru600.domain.News;
import com.svnavigatoru600.repository.news.impl.FindAllOrderedArguments;

/**
 * @author <a href="mailto:skalicky.tomas@gmail.com">Tomas Skalicky</a>
 */
public interface NewsDao {

    /**
     * Returns a {@link News} stored in the repository which has the given ID.
     */
    News findById(int newsId);

    /**
     * Returns all {@link News} stored in the repository arranged according to the given {@link FindAllOrderedArguments
     * arguments}.
     */
    List<News> findAllOrdered(FindAllOrderedArguments arguments);

    /**
     * Updates the given {@link News} in the repository. The old version of this news should be already stored there.
     */
    void update(News news);

    /**
     * Stores the given {@link News} to the repository.
     * 
     * @return The new ID of the given {@link News} generated by the repository
     */
    int save(News news);

    /**
     * Deletes the given {@link News} from the repository.
     */
    void delete(News news);
}
